In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.base.model import GenericLikelihoodModel
from scipy.optimize import minimize



/Users/rick.shapiro/anaconda/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [2]:
N = 10000
x = 10 + 2*np.random.randn(N)
y = 5 + x + np.random.randn(N)
df = pd.DataFrame({'y':y, 'x':x})
df['constant'] = 1

df.head()

x          y  constant
0   6.633616  11.315415         1
1  10.363870  16.033613         1
2  11.748170  15.580518         1
3  16.059475  23.227321         1
4  10.190862  15.794925         1

Maximum Likelihood Estimation is finding the parameters for a distribution that maximize the cumulative probability of the obeserved data.

In [27]:
def neg_loglike(theta):
    # generate a normal distribution for each predicted value of y
    # the models prediction is the mean of the distribution
    # standard deviation is a parameter to be optimized
    const,coef,std = theta
    print(const,coef,std)
    mu = const + coef*x
    return -1*stats.norm(mu, std).logpdf(y).sum() 

In [28]:
seed = np.array([1,1,1])
res = minimize(neg_loglike, seed, method = 'Nelder-Mead', 
                options={'disp': True})

1.0 1.0 1.0
1.05 1.0 1.0
1.0 1.05 1.0
1.0 1.0 1.05
1.03333333333 1.03333333333 1.03333333333
0.972222222222 1.05555555556 1.05555555556
0.933333333333 1.08333333333 1.08333333333
0.977777777778 1.11111111111 1.02777777778
0.966666666667 1.16666666667 1.01666666667
0.9 1.16666666667 1.03333333333
0.866666666667 1.22777777778 1.08888888889
0.8 1.31666666667 1.13333333333
0.844444444444 1.35 1.03888888889
0.8 1.48333333333 1.01666666667
0.840740740741 1.38888888889 1.09259259259
0.811111111111 1.5 1.12222222222
0.69012345679 1.53703703704 1.15987654321
0.759259259259 1.44444444444 1.12407407407
0.82962962963 1.47222222222 1.03703703704
0.822222222222 1.43333333333 1.06111111111
0.77037037037 1.49444444444 1.1462962963
0.825925925926 1.38611111111 1.06574074074
0.795061728395 1.37962962963 1.12716049383
0.881893004115 1.32530864198 1.06625514403
0.789917695473 1.41466049383 1.10961934156
0.79122085048 1.40267489712 1.15384087791
0.773868312757 1.41095679012 1.1978909465
0.807956104252 1.43

In [50]:
res.x # optimal coef, beta and std 

array([ 5.08709768,  0.99214399,  1.00056609])

Interpretation is - that these parameters generate a set of normal distributions that maximize the probability of seeing y in the distribution..?

In [43]:
mu = [5,10,13]
std = [1,3,5]
n = stats.norm(mu, std)
prob6 = n.pdf(6).round(9)
log_prob6 = np.log(prob6)

In [44]:
prob6

array([ 0.24197072,  0.05467002,  0.02994549])

In [45]:
log_prob6

array([-1.41893853, -2.90643971, -3.50837645])

In [46]:
n.logpdf(6)

array([-1.41893853, -2.90643971, -3.50837645])